/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalView.java
 *
 * Created on 16/11/2022, 15:42:15
 */
package controledeestoque.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class PrincipalView extends javax.swing.JFrame {

    /** Creates new form PrincipalView */
    public PrincipalView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new javax.swing.JPanel();
        labelControleDeEstoque = new javax.swing.JLabel();
        jBInserir = new javax.swing.JButton();
        jBBaixar = new javax.swing.JButton();
        jBRelatorio = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        tabbedPaneCentral = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelControleDeEstoque.setFont(new java.awt.Font("Tahoma", 1, 14));
        labelControleDeEstoque.setText("Controle de Estoque");

        jBInserir.setText("Inserir Produtos");
        jBInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInserirActionPerformed(evt);
            }
        });

        jBBaixar.setText("Baixar Produtos");
        jBBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBaixarActionPerformed(evt);
            }
        });

        jBRelatorio.setText("Relatório de Estoque");

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBaixar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSair))
                    .addGroup(panelBotoesLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(labelControleDeEstoque))
                    .addGroup(panelBotoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPaneCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelControleDeEstoque)
                .addGap(11, 11, 11)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInserir)
                    .addComponent(jBBaixar)
                    .addComponent(jBRelatorio)
                    .addComponent(jBSair))
                .addGap(18, 18, 18)
                .addComponent(tabbedPaneCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
// TODO add your handling code here:
    if (JOptionPane.showConfirmDialog(this, "Deseja mesmo fechar o sistema?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);
    }
}//GEN-LAST:event_jBSairActionPerformed

private void jBInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInserirActionPerformed
// TODO add your handling code here:
    tabbedPaneCentral.removeAll();;
    tabbedPaneCentral.add("Inserir Produtos", new InserirProdutosView());
    tabbedPaneCentral.validate();
    tabbedPaneCentral.repaint();
}//GEN-LAST:event_jBInserirActionPerformed

private void jBBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBaixarActionPerformed
// TODO add your handling code here:
    tabbedPaneCentral.removeAll();;
    tabbedPaneCentral.add("Baixar Produtos", new BaixarProdutosView());
    tabbedPaneCentral.validate();
    tabbedPaneCentral.repaint();
}//GEN-LAST:event_jBBaixarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBaixar;
    private javax.swing.JButton jBInserir;
    private javax.swing.JButton jBRelatorio;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel labelControleDeEstoque;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JTabbedPane tabbedPaneCentral;
    // End of variables declaration//GEN-END:variables
}
